# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Docklens < Formula
  desc "A terminal UI for managing Docker containers, images, volumes, and networks."
  homepage "https://github.com/L-Jayawardhana/DockLens"
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/L-Jayawardhana/DockLens/releases/download/v1.0.0/docklens_1.0.0_darwin_amd64.tar.gz"
      sha256 "0aec3590ba4df5d9332dc342914eca429fd43617f83d3a8e8931c29f7f84fb28"

      define_method(:install) do
        bin.install "docklens"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/L-Jayawardhana/DockLens/releases/download/v1.0.0/docklens_1.0.0_darwin_arm64.tar.gz"
      sha256 "17095e7f51d1fadce382d78610b79b8e4c404652d09e628666e2a0533789e539"

      define_method(:install) do
        bin.install "docklens"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/L-Jayawardhana/DockLens/releases/download/v1.0.0/docklens_1.0.0_linux_amd64.tar.gz"
      sha256 "4e1f43f53e8d3ffa441882bb03712a540cc1385a17bdb04c7b27ce6f34779d90"
      define_method(:install) do
        bin.install "docklens"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/L-Jayawardhana/DockLens/releases/download/v1.0.0/docklens_1.0.0_linux_arm64.tar.gz"
      sha256 "a9ce599f6e3608008abcad625cce67e98a74bbeba50f21296b3103517d1c80a8"
      define_method(:install) do
        bin.install "docklens"
      end
    end
  end

  test do
    system "#{bin}/docklens", "--version"
  end
end
