# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Docklens < Formula
  desc "A terminal UI for managing Docker containers, images, volumes, and networks."
  homepage "https://github.com/L-Jayawardhana/DockLens"
  version "2.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/L-Jayawardhana/DockLens/releases/download/v2.0.0/docklens_2.0.0_darwin_amd64.tar.gz"
      sha256 "bc84fa6ec736ab944256b5ebacb9a346615931fc7485ab630531598ee4a3c2d5"

      define_method(:install) do
        bin.install "docklens"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/L-Jayawardhana/DockLens/releases/download/v2.0.0/docklens_2.0.0_darwin_arm64.tar.gz"
      sha256 "19bd88f0b0e56d2aa3f2e38f930cb8f6913f71050fefa6a27df146aaa8348d53"

      define_method(:install) do
        bin.install "docklens"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/L-Jayawardhana/DockLens/releases/download/v2.0.0/docklens_2.0.0_linux_amd64.tar.gz"
      sha256 "bed6f1a5f222a8a6e4478cdc7ab42b8a1abacbc8144a42e9c496a575dd5eccf6"
      define_method(:install) do
        bin.install "docklens"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/L-Jayawardhana/DockLens/releases/download/v2.0.0/docklens_2.0.0_linux_arm64.tar.gz"
      sha256 "cb9c250ecbb0559933fb54f77dad8de89fd47d3583589c6f9e9dff8b01f876d1"
      define_method(:install) do
        bin.install "docklens"
      end
    end
  end

  test do
    system "#{bin}/docklens", "--version"
  end
end
