# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Docklens < Formula
  desc "A terminal UI for managing Docker containers, images, volumes, and networks."
  homepage "https://github.com/L-Jayawardhana/DockLens"
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/L-Jayawardhana/DockLens/releases/download/v1.0.0/docklens_1.0.0_darwin_amd64.tar.gz"
      sha256 "6895af69a9f896a0cd475ee661821fd9e9a9f2b4d80cab22fe016d5f0603c9a9"

      define_method(:install) do
        bin.install "docklens"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/L-Jayawardhana/DockLens/releases/download/v1.0.0/docklens_1.0.0_darwin_arm64.tar.gz"
      sha256 "7695571189bab7004a4ccb8852e15a77825acf989532212bd7ba90e282994dcf"

      define_method(:install) do
        bin.install "docklens"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/L-Jayawardhana/DockLens/releases/download/v1.0.0/docklens_1.0.0_linux_amd64.tar.gz"
      sha256 "bfc33a3c5850f4bbd19e1a9dd6970bb277dbe824623d78c05660f924b5908cde"
      define_method(:install) do
        bin.install "docklens"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/L-Jayawardhana/DockLens/releases/download/v1.0.0/docklens_1.0.0_linux_arm64.tar.gz"
      sha256 "5ef7eb83be9d721a084e26f35b9914aa1661761f29b91aa45b497953b7b8cacf"
      define_method(:install) do
        bin.install "docklens"
      end
    end
  end

  test do
    system "#{bin}/docklens", "--version"
  end
end
